version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pongbot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yfxm95mr84nl"
s3_prefix = "pongbot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
