AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.getUsers
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users
            Method: get
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.getGames
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /games
            Method: get
  SlackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: index.slackHandler
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        Slack:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /slack
            Method: post
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      TableName: Users
      BillingMode: PAY_PER_REQUEST
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      TableName: Games
      BillingMode: PAY_PER_REQUEST


Outputs:
  SlackApi:
    Description: "API Gateway endpoint URL for Prod stage for Slack"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack/"
  GetUsersApi:
    Description: "API Gateway endpoint URL for Prod stage to get users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  GetUsersFunction:
    Description: "Pongbot GetUsers Function ARN"
    Value: !GetAtt GetUsersFunction.Arn
  SlackFunction:
    Description: "Pongbot Slack Function ARN"
    Value: !GetAtt SlackFunction.Arn
