AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.getUsers
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users
            Method: get
  GetGamesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.getGames
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /games
            Method: get
  ChallengeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: index.challengeHandler
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
          GAMES_TABLE: !Ref GamesTable
      Events:
        Challenge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /challenge
            Method: post
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TableName: Users
      BillingMode: PAY_PER_REQUEST
  GamesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      TableName: Games
      BillingMode: PAY_PER_REQUEST


Outputs:
  ChallengeApi:
    Description: "API Gateway endpoint URL for Prod stage for challenges"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/challenge/"
  GetUsersApi:
    Description: "API Gateway endpoint URL for Prod stage to get users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  GetUsersFunction:
    Description: "Pongbot GetUsers Function ARN"
    Value: !GetAtt GetUsersFunction.Arn
  ChallengeFunction:
    Description: "Pongbot Challenge Function ARN"
    Value: !GetAtt ChallengeFunction.Arn
