AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetUsersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: index.getUsers
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /users
            Method: get
  ChallengeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: app/
      Handler: index.challengeHandler
      Runtime: nodejs12.x
      Policies: AmazonDynamoDBFullAccess
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Events:
        Challenge:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /challenge
            Method: post
  UsersTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      TableName: Users


Outputs:
  ChallengeApi:
    Description: "API Gateway endpoint URL for Prod stage for challenges"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/challenge/"
  GetUsersApi:
    Description: "API Gateway endpoint URL for Prod stage to get users"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  GetUsersFunction:
    Description: "Pongbot GetUsers Function ARN"
    Value: !GetAtt GetUsersFunction.Arn
  ChallengeFunction:
    Description: "Pongbot Challenge Function ARN"
    Value: !GetAtt ChallengeFunction.Arn
